"""
Grid-cell zones — the Milestone 1 deliverable: a bounding region divided
into square cells, each scored 0-100 for relief-priority severity based
on nearby disaster events, building density, population exposure, and
distance to the nearest resource depot (see
app/services/zones/grid_classifier.py for the scoring formula and its
honesty caveats).
"""

from datetime import datetime, timezone

from beanie import Document
from pydantic import Field
from pymongo import ASCENDING, GEOSPHERE, IndexModel

from app.models.disaster_event import GeoPoint


class GridCell(Document):
    grid_run_id: str  # groups all cells generated by one /zones/generate call
    row: int
    col: int
    geometry: dict  # GeoJSON Polygon (the cell boundary)
    centroid: GeoPoint

    severity_score: float = 0.0  # 0-100
    event_component: float = 0.0
    building_component: float = 0.0
    population_component: float = 0.0
    resource_component: float = 0.0

    contributing_event_ids: list[str] = Field(default_factory=list)
    building_count: int = 0
    nearest_resource_km: float | None = None

    computed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "grid_cells"
        indexes = [
            IndexModel([("grid_run_id", ASCENDING)], name="idx_grid_run_id"),
            IndexModel([("centroid", GEOSPHERE)], name="geo_2dsphere"),
            IndexModel([("severity_score", ASCENDING)], name="idx_severity_score"),
        ]
