"""Initial schema

Revision ID: 31dd78053125
Revises: 
Create Date: 2026-08-23 09:44:01.625681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '31dd78053125'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('gdacs', 'usgs', 'ndma', name='sourceenum'), nullable=False),
    sa.Column('event_type', sa.Enum('flood', 'earthquake', 'cyclone', 'drought', 'wildfire', 'other', name='eventtypeenum'), nullable=False),
    sa.Column('alert_level', sa.Enum('green', 'orange', 'red', 'low', 'medium', 'high', 'critical', name='alertlevelenum'), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('impact_extent', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('population_exposed', sa.Integer(), nullable=True),
    sa.Column('buildings_affected', sa.Integer(), nullable=True),
    sa.Column('critical_infrastructure_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


    op.create_table('resource_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('food', 'water', 'medical', 'shelter', 'vehicle', 'other', name='resourcetypeenum'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('depot_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'deployed', 'depleted', name='resourcestatusenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('grid_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cell_geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('related_event_id', sa.UUID(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('population_exposed', sa.Integer(), nullable=True),
    sa.Column('predicted_demand_food', sa.Float(), nullable=True),
    sa.Column('predicted_demand_water', sa.Float(), nullable=True),
    sa.Column('predicted_demand_medical', sa.Float(), nullable=True),
    sa.Column('predicted_demand_shelter', sa.Float(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priorityenum'), nullable=True),
    sa.Column('priority_override', sa.Enum('low', 'medium', 'high', name='priorityenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_event_id'], ['disaster_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('allocation_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('food', 'water', 'medical', 'shelter', 'vehicle', 'other', name='resourcetypeenum'), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('source_depot_id', sa.UUID(), nullable=False),
    sa.Column('coverage_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plan_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_depot_id'], ['resource_items.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['grid_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('predicted_food', sa.Float(), nullable=False),
    sa.Column('predicted_water', sa.Float(), nullable=False),
    sa.Column('predicted_medical', sa.Float(), nullable=False),
    sa.Column('predicted_shelter', sa.Float(), nullable=False),
    sa.Column('confidence_interval_low', sa.JSON(), nullable=True),
    sa.Column('confidence_interval_high', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recalibration_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['grid_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_run_id', sa.UUID(), nullable=False),
    sa.Column('depot_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Float(), nullable=False),
    sa.Column('is_fallback_straight_line', sa.Boolean(), nullable=True),
    sa.Column('road_status', sa.Enum('open', 'blocked', 'unknown', name='roadstatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['resource_items.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['grid_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priorityenum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_transit', 'delivered', 'cancelled', name='missionstatusenum'), nullable=True),
    sa.Column('supplies', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('status_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['grid_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')

    op.drop_table('routes')
    op.drop_table('prediction_records')
    op.drop_table('allocation_plans')

    op.drop_table('grid_cells')

    op.drop_table('resource_items')


    op.drop_table('disaster_events')
    # ### end Alembic commands ###
